- bom/pom.xml
- distribution/pom.xml
- distribution/src/main/assembly/dist.xml
- modules/eap/pom.xml
- modules/wildfly/pom.xml
Hello can you guys have alook a the resulting distribution package and let me know?
It should be similar to the previous one, except for:
- There is on optional folder containing parboiled and hibernate search dependencies
- core contains hibernate-ogm-core and all the required dependencies
> OGM-716 FIx distirbution package

- documentation/manual/src/main/asciidoc/en-US/modules/neo4j.asciidoc
Also added to the site's FAQ in parallel
> OGM-736 Move Neo4J + Transaction requirement as CAUTION

- core/src/main/java/org/hibernate/ogm/cfg/impl/InternalProperties.java
There you go, @hferentschik :)
> OGM-757 Document InternalProperties#OGM_ON

- core/src/main/java/org/hibernate/ogm/cfg/OgmConfiguration.java
- core/src/main/java/org/hibernate/ogm/cfg/impl/HibernateSearchIntegration.java
- core/src/main/java/org/hibernate/ogm/jpa/HibernateOgmPersistence.java
- core/src/main/java/org/hibernate/ogm/query/impl/FullTextSearchQueryTranslator.java
- core/src/test/java/org/hibernate/ogm/backendtck/hsearch/HibernateSearchAtopOgmTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/hsearch/SearchOnStandaloneOGMTest.java
- documentation/manual/src/main/asciidoc/en-US/modules/query.asciidoc
https://hibernate.atlassian.net/browse/OGM-171
> OGM-171 Automate setting the FIND_BY_ID strategy on fulltext queries

- documentation/manual/pom.xml
- documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
- https://hibernate.atlassian.net/browse/OGM-761
> OGM-761 Clarify need to download the Hibernate Search modules separately

- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/Neo4jDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/impl/StringLoggerToJBossLoggingAdaptor.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/logging/impl/Log.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/Neo4jGraphDatabaseServiceLoaderTest.java
Used for query execution today
> OGM-775 Create an adaptor from JBoss Logging to Neo4J StringLogger

- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/EmbeddedAliasTree.java
The missing fix to the javadoc for [OGM-692](https://hibernate.atlassian.net/projects/OGM/issues/OGM-692)
> OGM-692 Fix EMbeddedAliasTree javadoc

- core/src/main/java/org/hibernate/ogm/service/impl/OgmIntegrator.java
- core/src/main/java/org/hibernate/ogm/service/impl/SchemaDefiningObserver.java
- https://hibernate.atlassian.net/browse/OGM-772
> OGM-772 Rename SchemaInitializingObserver as SchemaDefiningObserver

- bom/pom.xml
- core/src/main/java/org/hibernate/ogm/massindex/impl/BatchCoordinator.java
- core/src/main/java/org/hibernate/ogm/massindex/impl/BatchIndexingWorkspace.java
- core/src/main/java/org/hibernate/ogm/massindex/impl/OgmMassIndexer.java
- core/src/main/java/org/hibernate/ogm/massindex/impl/TupleIndexer.java
- modules/wildfly/pom.xml
- pom.xml
blockers to move to WF9 :
- https://hibernate.atlassian.net/browse/OGM-822
- https://hibernate.atlassian.net/browse/OGM-823
> Components upgrade

- core/src/main/java/org/hibernate/ogm/query/parsing/impl/ParserPropertyHelper.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/Ending.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/OptionalStoryBranch.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedCollectionTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/StoryBranch.java
- documentation/manual/src/main/asciidoc/en-US/modules/mongodb.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/neo4j.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/query.asciidoc
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/dialect/impl/MongoDBTupleSnapshot.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/dialect/impl/MongoHelpers.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/impl/MongoDBQueryDescriptor.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/impl/MongoDBQueryParsingResult.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/impl/MongoDBQueryRendererDelegate.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/nativequery/impl/MongoDBQueryDescriptorBuilder.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/MongoDBQueryDescriptorSerializationTest.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/Neo4jQueryRendererDelegate.java
https://hibernate.atlassian.net/browse/OGM-781
Support projection of properties in embedded collections. This will only work for Neo4j and MongoDB.
The projection of a collection does not work at the moment in hibernate search, it will only return the first element and not all the elements of the collection stored in the index.
> OGM-781 Support projections for embedded collections

- pom.xml
https://hibernate.atlassian.net/browse/OGM-868
It will add to the Manifest of the jars an entry called git-commit-id. Example:
```
Git-Commit-Id: f2b416ae402a9101f0fca8521bf4c3c86055cf96                                                   
```
> OGM-868 Include git commit in the MANIFEST

- integrationtest/couchdb/pom.xml
- integrationtest/redis/pom.xml
- integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationIT.java
- integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationWithTTLConfiguredIT.java
- integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisTestProperties.java
https://hibernate.atlassian.net/browse/OGM-896
> OGM-896 Start Redis and CouchDB integration tests only when required

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-810
This version will work with   MongoDB Driver 3
> OGM-810 Update Fongo to version 2.0.2

- bom/pom.xml
- core/src/test/java/org/hibernate/ogm/test/boot/StandAloneOgmTest.java
- documentation/manual/src/main/asciidoc/en-US/modules/api.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/architecture.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/cassandra.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
- documentation/manual/src/main/asciidoc/en-US/modules/getting-started.asciidoc
@DavideD Can you check out this one? Thx!
> OGM-903, OGM-864

- documentation/manual/src/main/asciidoc/en-US/modules/mongodb.asciidoc
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/MongoDBSessionCLIQueryTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/parsing/nativequery/NativeQueryParserTest.java
https://hibernate.atlassian.net/browse/OGM-927
In the end we already support this type of queries, the problem was in the missing quotes.
I've just added some tests and updated the documentation.
> OGM-927 MongoDB CLI logical operator

- core/src/main/java/org/hibernate/ogm/loader/impl/OgmLoader.java
- core/src/test/java/org/hibernate/ogm/backendtck/callbacks/Animal.java
- core/src/test/java/org/hibernate/ogm/backendtck/callbacks/PostLoadTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/callbacks/Zoo.java
Added functionality and unit test.
> OGM-933 Added PostLoad annotation support

- cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/CassandraDialect.java
- cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/impl/CassandraSchemaDefiner.java
- cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/logging/impl/Log.java
- cassandra/src/test/java/org/hibernate/ogm/datastore/cassandra/test/query/nativequery/CassandraEntityManagerNativeQueryTest.java
- cassandra/src/test/java/org/hibernate/ogm/datastore/cassandra/test/query/nativequery/CassandraSessionNativeQueryTest.java
- cassandra/src/test/java/org/hibernate/ogm/datastore/cassandra/test/query/nativequery/OscarWildePoem.java
- core/src/test/java/org/hibernate/ogm/utils/TestHelper.java
* Applying grid type conversion to parameter values
* Raising warning due to unmappable multi-column indexes
Hey @jhalliday, any feedback on this one?
> OGM-909 Follow up to parameterized queries in Cassandra

- bom/pom.xml
- modules/wildfly/src/main/assembly/dist.xml
- modules/wildfly/src/main/modules/ogm/neo4j-internal/module.xml
- modules/wildfly/src/main/modules/ogm/neo4j/module.xml
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/Neo4jDialect.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/Neo4jGraphDatabaseServiceLoaderTest.java
https://hibernate.atlassian.net/projects/OGM/issues/OGM-972
* Upgrade Neo4j version to 2.3.2
* Fix compilation and test errors
* Update WildFly modules
> OGM-972 Upgrade to Neo4j 2.3.2

- bom/pom.xml
- documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
- integrationtest/pom.xml
- modules/wildfly/pom.xml
https://hibernate.atlassian.net/browse/OGM-993
> OGM-993 Modules for Infinispan should use the Infinispan community modules rather than the WildFly ones

- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/impl/MongoDBQueryDescriptor.java
https://hibernate.atlassian.net/browse/OGM-995
> OGM-995 Fix javadoc

- core/src/test/java/org/hibernate/ogm/backendtck/associations/collection/types/User.java
- core/src/test/java/org/hibernate/ogm/test/associations/AssociationKeyMetadataEqualityTest.java
https://hibernate.atlassian.net/browse/OGM-969
> OGM-969 MapTest fix

- redis/src/main/java/org/hibernate/ogm/datastore/redis/RedisJsonDialect.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/impl/RedisDatastoreProvider.java
https://hibernate.atlassian.net/browse/OGM-1004
> OGM-1004 Fix javadoc causing build failure

- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/test/dialect/CouchDBDialectTest.java
- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/test/dialect/backend/impl/CouchDBDatastoreTest.java
- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/utils/CouchDBTestHelper.java
- integrationtest/neo4j/src/test/java/org/hibernate/ogm/test/integration/jboss/Neo4jJtaModuleMemberRegistrationIT.java
- integrationtest/neo4j/src/test/java/org/hibernate/ogm/test/integration/jboss/Neo4jResourceLocalModuleMemberRegistrationIT.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java
- performance/pom.xml
- performance/src/main/java/org/hibernate/ogm/perftest/mongodb/nativeapi/NativeApiBenchmarkBase.java
- https://hibernate.atlassian.net/browse/OGM-1009
> OGM-1009 Minor resource leaks in integration tests

- documentation/manual/pom.xml
- documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
- integrationtest/couchdb/src/test/resources/jboss-deployment-structure-couchdb.xml
- integrationtest/mongodb/src/test/java/org/hibernate/ogm/test/integration/jboss/MongoDBModuleMemberRegistrationIT.java
- integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationIT.java
- integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationWithTTLConfiguredIT.java
- integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/EhcacheModuleMemberRegistrationIT.java
- integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/InfinispanModuleMemberRegistrationIT.java
- integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/MagiccardsDatabaseScenario.java
- integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/ModulesMagicDeckITCassandra.java
- integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/SearchIntegrationIT.java
- integrationtest/testcase/src/test/resources/jboss-deployment-structure-ehcache.xml
- pom.xml
- https://hibernate.atlassian.net/browse/OGM-1010
> OGM-1010 cleanup need of depending to the Search module

- documentation/manual/src/main/asciidoc/en-US/modules/getting-started.asciidoc
https://hibernate.atlassian.net/browse/OGM-409
> OGM-899 Fix typo 'Max OS X'

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1036
- https://hibernate.atlassian.net/browse/OGM-1037
> Search upgrade

- core/src/main/java/org/hibernate/ogm/util/impl/ArrayHelper.java
- core/src/test/java/org/hibernate/ogm/util/impl/ArrayHelperTest.java
https://hibernate.atlassian.net/browse/OGM-1013
I've squashed the PR sent by @schernolyas and separate the changes to fix the checkstyle rule
https://github.com/hibernate/hibernate-ogm/pull/656
> OGM-1013 ArrayHelper unit tests

- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/transaction/impl/Neo4jJtaTransactionCoordinator.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/transaction/impl/Neo4jLocalTransactionCoordinator.java
https://hibernate.atlassian.net/browse/OGM-1039
> OGM-1039 Fix javadoc for embedded Neo4j transaction coordinators

- documentation/manual/src/main/asciidoc/en-US/modules/mongodb.asciidoc
Supersedes https://github.com/hibernate/hibernate-ogm/pull/667 .
> OGM-1027 Mention in the documentation which functions are supported

- core/src/main/java/org/hibernate/ogm/type/descriptor/impl/ByteMappedGridTypeDescriptor.java
- core/src/main/java/org/hibernate/ogm/type/descriptor/impl/LongMappedGridTypeDescriptor.java
- core/src/main/java/org/hibernate/ogm/type/impl/ByteArrayStringType.java
- core/src/main/java/org/hibernate/ogm/type/impl/ByteMappedType.java
- core/src/main/java/org/hibernate/ogm/type/impl/LongMappedType.java
- core/src/main/java/org/hibernate/ogm/type/impl/PrimitiveByteArrayMappedType.java
- core/src/main/java/org/hibernate/ogm/type/impl/PrimitiveByteArrayStringType.java
https://hibernate.atlassian.net/browse/OGM-1054
New type descriptors for Neo4j remote, I've added them in core as they might come handy in the future for other dialects.
> OGM-1054 Additional type descriptors

- bom/pom.xml
- documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
- integrationtest/pom.xml
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/cassandra/ModulesMagicDeckIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/couchdb/CouchDBModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/ehcache/EhcacheModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/ehcache/EhcacheModuleMemberRegistrationUsingJBossDeploymentStructureIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/infinispan/InfinispanModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/infinispan/SearchIntegrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/mongodb/MongoDBModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/neo4j/Neo4jJtaModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/neo4j/Neo4jResourceLocalModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/redis/RedisModuleMemberRegistrationIT.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/redis/RedisModuleMemberRegistrationWithTTLConfiguredIT.java
- jipijapa/pom.xml
- jipijapa/src/main/java/org/wildfly/jpa/hibernateogm5/HibernateOGMPersistenceProviderAdaptor.java
- jipijapa/src/main/resources/META-INF/services/org.jipijapa.plugin.spi.PersistenceProviderAdaptor
- modules/pom.xml
- modules/wildfly/pom.xml
- modules/wildfly/src/main/assembly/dist.xml
- modules/wildfly/src/main/modules/ogm/core/module.xml
- modules/wildfly/src/main/modules/ogm/jipijapa/module.xml
- pom.xml
- https://hibernate.atlassian.net/browse/OGM-828
> Automatic integration in WildFly

- core/src/main/java/org/hibernate/ogm/dialect/batch/spi/OperationsQueue.java
- core/src/main/java/org/hibernate/ogm/dialect/eventstate/impl/EventStateLifecycles.java
- core/src/main/java/org/hibernate/ogm/dialect/impl/BatchOperationsDelegator.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/dialectinvocations/GridDialectOperationInvocationsTest.java
https://hibernate.atlassian.net/browse/OGM-1068
https://hibernate.atlassian.net/browse/OGM-1069
https://hibernate.atlassian.net/browse/OGM-1070
Assorted small fixes to the batch support (extracted from a bigger patch).
> Assorted small fixes to the batch support

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1072
A simle one before upgrading to 3
> OGM-1072 Update Neo4j to version 2.3.4

- src/build-scripts/dbmanager.sh
https://hibernate.atlassian.net/browse/OGM-1084
> OGM-1084 Add script to run docker containers for OGM databases

- integrationtest/src/test/java/org/hibernate/ogm/test/integration/infinispan/SearchIntegrationIT.java
Made the test consistent with similar other tests.
> OGM-1051 Remove an unused variable

- core/src/main/java/org/hibernate/ogm/jdbc/impl/NoopConnection.java
- core/src/main/java/org/hibernate/ogm/jdbc/impl/NoopDatabaseMetaData.java
- core/src/main/java/org/hibernate/ogm/jdbc/impl/NoopStatement.java
- core/src/main/java/org/hibernate/ogm/massindex/impl/Executors.java
- core/src/main/java/org/hibernate/ogm/type/impl/DoubleType.java
- core/src/main/java/org/hibernate/ogm/type/impl/LongMappedType.java
- core/src/main/java/org/hibernate/ogm/type/impl/LongType.java
- core/src/main/java/org/hibernate/ogm/type/impl/WrapperBinaryType.java
- core/src/test/java/org/hibernate/ogm/utils/jpa/GetterPersistenceUnitInfo.java
- core/src/test/java/org/hibernate/ogm/utils/jpa/NoopDatasource.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/options/AuthenticationMechanismType.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/dialect/impl/EmbeddedNeo4jAssociationQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/dialect/impl/RemoteNeo4jNodesTupleIterator.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/impl/RemoteNeo4jClient.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/transaction/impl/RemoteNeo4jResourceLocalTransactionCoordinator.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/transaction/impl/RemoteNeo4jTransaction.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/impl/Base64ByteArrayTypeDescriptor.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/options/navigation/impl/RedisPropertyContextImpl.java
https://hibernate.atlassian.net/browse/OGM-1092
> OGM-1092 Add missing @Override annotations

- pom.xml
It fixes a memory issue during build.
https://hibernate.atlassian.net/browse/OGM-1102
> OGM-1102 Upgrade maven-jar-plugin to 3.0.1

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1109
> OGM-1109 Upgrade Neo4j to 2.3.5

- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/RemoteNeo4jDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/dialect/impl/EmbeddedNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/dialect/impl/NodeWithEmbeddedNodes.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/dialect/impl/RemoteNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/dialect/impl/RemoteNeo4jNodesTupleIterator.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/dialect/impl/RemoteNeo4jTupleSnapshot.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/util/impl/RemoteNeo4jHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/query/Neo4jEntityQueriesTest.java
https://hibernate.atlassian.net/browse/OGM-1075
All embedded associated to an entity, should be loaded when the entity is loaded.
This commit fix the previous behaviour of making a request to the server for each embedded
column.
> OGM-1075 Make sure embedded are loaded correctly in Neo4j remote

- bom/pom.xml
- neo4j/pom.xml
https://hibernate.atlassian.net/browse/OGM-1117
> OGM-1117 Enable enforcer plugin for Neo4j

- src/main/release-scripts/upload-documentation.sh
https://hibernate.atlassian.net/browse/OGM-1124
We need to install on the build server (if not already available):
* wget
* sed
* jq
> OGM-1124 Update doc server metadata on release

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1128
> OGM-1128 Upgrade to Infinispan 8.2.3.Final

- core/src/main/java/org/hibernate/ogm/dialect/impl/AssociationTypeContextImpl.java
- core/src/main/java/org/hibernate/ogm/dialect/spi/AssociationTypeContext.java
- core/src/main/java/org/hibernate/ogm/persister/impl/EntityAssociationUpdater.java
- core/src/main/java/org/hibernate/ogm/persister/impl/OgmCollectionPersister.java
- core/src/main/java/org/hibernate/ogm/persister/impl/OgmEntityPersister.java
- core/src/test/java/org/hibernate/ogm/utils/GridDialectOperationContexts.java
- documentation/manual/src/main/asciidoc/en-US/modules/redis.asciidoc
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/loading/LoadSelectedColumnsCollectionTest.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/RedisJsonDialect.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/impl/json/JsonEntityStorageStrategy.java
- redis/src/test/java/org/hibernate/ogm/datastore/redis/test/options/ttl/BandWithAssociationStoredInEntity.java
- redis/src/test/java/org/hibernate/ogm/datastore/redis/test/options/ttl/GlobalPropertyTTLTest.java
, not the one of the association
Clarify this in the documentation.
> OGM-1084 In the case of an association stored in the entity, the TTL should be the one of the entity

- bom/pom.xml
* https://hibernate.atlassian.net/browse/OGM-1133
> OGM-1133 Update the Cassandra driver to 3.1.0

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1130
> OGM-1130 Upgrade to Hibernate HQL Parser version 1.3.0.Final

- cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/impl/CassandraSequenceHandler.java
- core/src/main/java/org/hibernate/ogm/model/key/spi/IdSourceKey.java
- couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/backend/impl/CouchDBDatastore.java
- ehcache/src/main/java/org/hibernate/ogm/datastore/ehcache/persistencestrategy/kind/impl/SerializableIdSourceKey.java
- ehcache/src/main/java/org/hibernate/ogm/datastore/ehcache/persistencestrategy/table/impl/PerTableSerializableIdSourceKey.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/kind/externalizer/impl/IdSourceKeyExternalizer.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/table/externalizer/impl/PersistentIdSourceKey.java
- infinispan/src/test/java/org/hibernate/ogm/datastore/infinispan/test/dialect/impl/IdSourceKeyExternalizerTest.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jSequenceGenerator.java
- redis/src/main/java/org/hibernate/ogm/datastore/redis/AbstractRedisDialect.java
- https://hibernate.atlassian.net/browse/OGM-1147
> OGM-1147 IdSourceKey doesn't need to handle multi column types

- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/test/embeddable/ElementCollectionOfEmbeddableWithNamedColumnMappingTest.java
- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/test/embeddable/EmbeddableMappingTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/ElementCollectionOfEmbeddableWithNamedColumnMappingTest.java
- redis/src/test/java/org/hibernate/ogm/datastore/redis/test/embeddable/ElementCollectionOfEmbeddableWithNamedColumnMappingTest.java
A couple of minor fixes that were left behind
> OGM-1151, OGM-893 Update comments and Jira in code

- core/src/test/java/org/hibernate/ogm/backendtck/queries/Helicopter.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/Hypothesis.java
- https://hibernate.atlassian.net/browse/OGM-1158
> OGM-1158 Some tests are missing @SortableField

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1182
> OGM-1182 Update Neo4j to version 3.0.6

- documentation/javadoc/pom.xml
- redis/src/main/java/org/hibernate/ogm/datastore/redis/AbstractRedisDialect.java
https://hibernate.atlassian.net/browse/OGM-1183
> OGM-1183 Fixes to the javadoc

- documentation/manual/src/main/asciidoc/en-US/modules/mapping.asciidoc
https://hibernate.atlassian.net/browse/OGM-1185
> OGM-1185 Update inheritance mapping paragraph

- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/InfinispanRemoteDialect.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/VersionedTuple.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protobuf/SchemaDefinitions.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/sequences/HotRodSequencer.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/logging/impl/Log.java
https://hibernate.atlassian.net/browse/OGM-353
Follows https://github.com/hibernate/hibernate-ogm/pull/781
@Sanne 
A couple of minor changes I spotted checking your PR
> Ogm 353 follow up

- core/src/main/java/org/hibernate/ogm/persister/impl/BiDirectionalAssociationHelper.java
- core/src/test/java/org/hibernate/ogm/test/persister/BiDirectionalAssociationHelperTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/associations/MultipleInverseAssociationOnTheSameEntityTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/associations/Node.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/associations/NodeLink.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/mapping/MappedLink.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/mapping/MappedNode.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/mapping/MultipleInverseAssociationOnTheSameEntityTest.java
See https://github.com/hibernate/hibernate-ogm/pull/786
> OGM-1198 For branch 5.0

- core/src/main/java/org/hibernate/ogm/loader/impl/OgmLoader.java
- core/src/main/java/org/hibernate/ogm/model/key/spi/AssociationKey.java
- core/src/main/java/org/hibernate/ogm/persister/impl/OgmCollectionPersister.java
- core/src/main/java/org/hibernate/ogm/util/impl/Contracts.java
- documentation/manual/src/main/asciidoc/en-US/modules/mapping.asciidoc
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- src/main/build-config/checkstyle.xml
@DavideD these are the commits I think are good candidates for 5.0.3 backports. Nothing much, but I think it's worth it nonetheless.
Issues to mark as fixVersion 5.0.3.Final once merged:
* https://hibernate.atlassian.net/browse/OGM-1157
* https://hibernate.atlassian.net/browse/OGM-1185
> 5.0.3 backport proposal

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1201
> OGM-1201 Upgrade embedded MongoDB to version 3.2.10

- documentation/manual/src/main/asciidoc/en-US/modules/datastore-providers.asciidoc
https://hibernate.atlassian.net/browse/OGM-1203
There is also a fix for OGM-1159
> OGM-1203 Documentation missing bits

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1214
> OGM-1214 Upgrade neo4j-java-driver to 1.0.6

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1217
- https://hibernate.atlassian.net/browse/OGM-1218
- https://hibernate.atlassian.net/browse/OGM-1219
- https://hibernate.atlassian.net/browse/OGM-1220
> Various upgrades

- core/src/main/java/org/hibernate/ogm/util/impl/Log.java
Corrected the Typo for datastore
> Corrected the typo for Datastore

- .travis.yml
* https://hibernate.atlassian.net/browse/OGM-1234
In prevision of the future Neo4j upgrades.
> OGM-1234 Travis - Get the Neo4j version from the pom file

- documentation/manual/src/main/asciidoc/en-US/modules/mongodb.asciidoc
- pom.xml
Currently master is not building because of the documentation.
I don't see anything odd in the latest changes I committed but for some reasons the build fails.
It seems that if I update the reosurces plugin everything works fine.
> Fix master

- core/src/main/java/org/hibernate/ogm/query/parsing/impl/ParserPropertyHelper.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedCollectionTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/StoryGame.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/impl/MongoDBPropertyHelper.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/Neo4jPropertyHelper.java
https://hibernate.atlassian.net/browse/OGM-913
This only works for Neo4j and MongoDB at the moment, I'll create a new issue for the lucene parser since it requires some changes in the HQL parser project
> OGM-913 Allows join on collection of elements

- README.md
@DavideD here is an attempt to make the README more up to date and less intimidating.
> Make the README file more up to date

- README.md
> Update JIRA URL

- core/src/main/java/org/hibernate/ogm/util/impl/CollectionHelper.java
* https://hibernate.atlassian.net/browse/OGM-1067
(copied from what we did in HV recently)
> OGM-1067 Avoid systematic resizing of collections when we provide a size

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1256
> OGM-1256 Upgrade to Hibernate Search 5.6.1.Final and Apache Lucene 5.5.4

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1257
> OGM-1257 Update neo4j-java-driver to version 1.1.2

- documentation/manual/pom.xml
- documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
- integrationtest/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/OGM-1260
@gsmet  Can you have a quick look at this one?
> OGM-1260 Expands WildFly 10 configuration paragraph

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1270
> OGM-1270 Upgrade Fongo to version 2.0.12

- cassandra/src/test/java/org/hibernate/ogm/datastore/cassandra/utils/CassandraTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/GridDialectTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/HashMapTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/TestHelper.java
- couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/utils/CouchDBTestHelper.java
- ehcache/src/test/java/org/hibernate/ogm/datastore/ehcache/utils/EhcacheTestHelper.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
- infinispan/src/test/java/org/hibernate/ogm/datastore/infinispan/utils/InfinispanTestHelper.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java
- redis/src/test/java/org/hibernate/ogm/datastore/redis/utils/RedisTestHelper.java
should be trivial, but I couldn't test all DBs. Relying on CI for that.
https://hibernate.atlassian.net/browse/OGM-588
> OGM-588 Revert work-around required due to ORM version update

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1277
> OGM-1277 Update to ORM 5.1.5

- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/BuiltinTypeMappingTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
https://hibernate.atlassian.net/browse/OGM-1281
@gsmet This PR add some check to make sure that the mapping of the binary value is not changed when we are going to apply https://github.com/hibernate/hibernate-ogm/pull/856
> OGM-1281 Test native mapping of binary values in MongoDB

- documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
- documentation/manual/src/main/asciidoc/modules/getting-started.asciidoc
- modules/src/main/aliases/org/hibernate/search/engine/module.xml
- modules/src/main/modules/org/hibernate/search/orm/module.xml
https://hibernate.atlassian.net/browse/OGM-1284
This should improve the paragraph related ot the configuration of WildFly.
@gsmet Can you have a look and let me know if it makes sense to you?
Thanks
> OGM-1284 wild fly configuration

- core/src/test/java/org/hibernate/ogm/backendtck/associations/recursive/RecursiveAssociationsTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/associations/recursive/TreeNode.java
- core/src/test/java/org/hibernate/ogm/utils/TestForIssue.java
- infinispan-remote/infinispan-server-testconfig/wildfly-trimmed-config.xml
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/BoltNeo4jDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/EmbeddedNeo4jDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/HttpNeo4jDialect.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/dialect/impl/EmbeddedNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/dialect/impl/EmbeddedNeo4jTupleAssociationSnapshot.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/bolt/dialect/impl/BoltNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/http/dialect/impl/HttpNeo4jEntityQueries.java
https://hibernate.atlassian.net/browse/OGM-1288
https://hibernate.atlassian.net/browse/OGM-1292
https://hibernate.atlassian.net/browse/OGM-1293
This is a follow up of @hholierhoek pr: https://github.com/hibernate/hibernate-ogm/pull/861
I've rebased on top of the grouping API: https://github.com/hibernate/hibernate-ogm/pull/862
@hholierhoek: I will work on OGM-1290 on a separate PR
@emmanuelbernard Any news about the CLA, can eventually his commit be included?
> OGM-1288 Recursive structures

- core/src/test/java/org/hibernate/ogm/backendtck/associations/manytoone/SameRoleNameDifferentTablesTest.java
- infinispan-remote/infinispan-server-testconfig/wildfly-trimmed-config.xml
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/associations/SameRoleNameDifferentTablesMappingTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/dialect/impl/EmbeddedNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/bolt/dialect/impl/BoltNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/http/dialect/impl/HttpNeo4jEntityQueries.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/http/impl/HttpNeo4jClient.java
https://hibernate.atlassian.net/browse/OGM-1290
> OGM-1290 'target' node in Neo4j association queries needs to be qualified with a label

- bom/pom.xml
* https://hibernate.atlassian.net/browse/OGM-1306
> OGM-1306 Upgrade Hibernate ORM to 5.1.10.Final

- neo4j/src/test/resources/hibernate.properties
- neo4j/src/test/resources/neo4j.conf
* https://hibernate.atlassian.net/browse/OGM-1309
This one is a simple one but very useful to stabilize the Neo4j embedded tests.
> OGM-1309 Set the max size of Neo4j page cache

- core/src/main/java/org/hibernate/ogm/dialect/query/spi/QueryParameters.java
- core/src/test/java/org/hibernate/ogm/utils/GridDialectTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/HashMapTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/TestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/jpa/OgmJpaTestRunner.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
- infinispan/src/test/java/org/hibernate/ogm/datastore/infinispan/utils/InfinispanTestHelper.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java
https://hibernate.atlassian.net/browse/OGM-1308
Follows up https://github.com/hibernate/hibernate-ogm/pull/874
> Schernolyas orient db ignite core changes

- README.md
- documentation/manual/src/main/asciidoc/modules/architecture.asciidoc
Add Apache Ignite dialect to Readme and manual
> Add Apache Ignite dialect to Readme and manual

- core/src/main/java/org/hibernate/ogm/massindex/impl/BatchCoordinator.java
I don't think it changes anything for now but as the rest of the code takes the tenant id into account, we should be consistent.
https://hibernate.atlassian.net/browse/OGM-1318
> OGM-1318 Pass the tenant id to PurgeAllLuceneWork

- bom/pom.xml
- documentation/examples/gettingstarted/src/main/resources/infinispan-local.xml
- documentation/manual/src/main/asciidoc/modules/getting-started.asciidoc
- documentation/manual/src/main/asciidoc/modules/infinispan.asciidoc
- infinispan-remote/pom.xml
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protobuf/SchemaDefinitions.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamSerializerSetup.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/logging/impl/Log.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/initialize/ProtoBufSchemaTest.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/InfinispanDialect.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/logging/impl/Log.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/impl/KeyProvider.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/impl/LocalCacheManager.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/kind/impl/OnePerKindKeyProvider.java
- infinispan/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/table/impl/PerTableKeyProvider.java
- infinispan/src/main/resources/org/hibernate/ogm/datastore/infinispan/default-config.xml
- infinispan/src/test/java/org/hibernate/ogm/datastore/infinispan/utils/InfinispanTestHelper.java
- infinispan/src/test/resources/infinispan-dist.xml
- infinispan/src/test/resources/infinispan-local.xml
- infinispan/src/test/resources/testing-flush-loopback.xml
- integrationtest/pom.xml
- integrationtest/src/test/resources/infinispan.xml
- jipijapa/pom.xml
- modules/pom.xml
Follow up on pr #881 
- https://hibernate.atlassian.net/browse/OGM-1269
- https://hibernate.atlassian.net/browse/OGM-1327
- https://issues.jboss.org/browse/ISPN-7006
> OGM updated to Infinispan 9.1.1

- bom/pom.xml
- modules/src/main/assembly/dist.xml
- modules/src/main/modules/ogm/neo4j-internal/module.xml
* https://hibernate.atlassian.net/browse/OGM-1332
> OGM-1332 Update Neo4j to 3.2.6 and Hibernate Search to 5.6.3.Final

- core/src/test/java/org/hibernate/ogm/utils/BaseGridDialectTestHelper.java
- core/src/test/java/org/hibernate/ogm/utils/HashMapTestHelper.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
- infinispan/src/test/java/org/hibernate/ogm/datastore/infinispan/utils/InfinispanTestHelper.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java
https://hibernate.atlassian.net/browse/OGM-1323
Not critical, but it makes our life easier if we need to add some methods.
> OGM-1323 base class for grid dialect test helper

- pom.xml
See task https://hibernate.atlassian.net/browse/OGM-1341
> OGM-1341 Update version of Byteman

- documentation/manual/src/main/asciidoc/modules/mongodb.asciidoc
* https://hibernate.atlassian.net/browse/OGM-1339
> OGM-1339 Add documentation for the MongoDB geospatial support

- .travis.yml
https://hibernate.atlassian.net/browse/OGM-1359
https://hibernate.atlassian.net/browse/OGM-1360
> OGM-1359 + OGM-1360 Travis build improvements

- bom/pom.xml
- documentation/examples/pom.xml
- documentation/javadoc/pom.xml
- documentation/manual/pom.xml
- integrationtest/pom.xml
- jipijapa/pom.xml
- modules/pom.xml
- performance/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/OGM-1362
https://hibernate.atlassian.net/browse/OGM-1363
> OGM-1362 + OGM-1363 Javadoc improvements

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1368
> OGM-1368 Upgrade to Infinispan 9.1.4

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1370
> OGM-1370 Upgrade to Apache Lucene 5.5.5

- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/nativequery/impl/NativeQueryParser.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/MongoDBSessionCLIQueryTest.java
https://hibernate.atlassian.net/browse/OGM-1371
A quick one found by a user: https://stackoverflow.com/questions/48056260/hibernate-ogm-with-mongodb-count-query-with-gt-gte-lt-lte-not-working-with-l
> OGM-1371 MongoDB native parser does not recognize 0 as integer

- bom/pom.xml
* https://hibernate.atlassian.net/browse/OGM-1378
> OGM-1378 Upgrade Neo4j to 3.3.2

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1381
> OGM-1381 Upgrade to Infinispan 9.1.5.Final

- documentation/manual/src/main/asciidoc/modules/datastore-providers.asciidoc
- documentation/manual/src/main/asciidoc/modules/mongodb.asciidoc
https://hibernate.atlassian.net/browse/OGM-1262
Most of it was removed when we split the repositories
> OGM-1262 Remove experimental features from doc

- bom/pom.xml
I referenced OGM-1229 as it's not worth creating a specific issue for it IMHO.
> OGM-1229 Upgrade Hibernate ORM to 5.2.13.Final

- bom/pom.xml
* https://hibernate.atlassian.net/browse/OGM-1399
> OGM-1399 Upgrade Neo4j to 3.3.3

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1401
> OGM-1401 Upgrade to Hibernate Commons Annotations 5.0.2.Final

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1404
> OGM-1404 Update Neo4j driver to version 1.5.1

- documentation/manual/pom.xml
- documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
- documentation/manual/src/main/asciidoc/modules/getting-started.asciidoc
- jipijapa/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/OGM-1414
> OGM-1414 Introducing wildfly-short-version parameter in the manual

- README.md
https://hibernate.atlassian.net/browse/OGM-1418
@fax4ever Easy one to review
> OGM-1418 Fix README.md about how to run the tests on a Neo4j server

- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/id/objectid/Bar.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/id/objectid/DoorMan.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/id/objectid/MusicGenre.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/id/objectid/ObjectIdJpaTest.java
https://hibernate.atlassian.net/browse/OGM-1434
> OGM-1434 Test case for MongoDB: ObjectId passed as parameter to query

- bom/pom.xml
- https://hibernate.atlassian.net/browse/OGM-1437
> OGM-1437 Upgrade to Hibernate Commons Annotations 5.0.3.Final

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1436
> OGM-1436 Upgrade to ORM 5.2.16

- documentation/manual/src/main/asciidoc/modules/mongodb.asciidoc
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/impl/MongoDBQueryDescriptor.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/nativequery/impl/NativeQueryParser.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/MarkTwainPoem.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/MongoDBSessionCLIQueryTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/parsing/nativequery/NativeQueryParserTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
https://hibernate.atlassian.net/browse/OGM-1433
Follows: https://github.com/hibernate/hibernate-ogm/pull/998
> OGM-1433 Support drop collection as native query for MongoDB

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1450
> OGM-1450 Upgrade to Hibernate Search 5.10.0.Beta2

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1453
> OGM-1453 Upgrade to Neo4j 3.3.5

- pom.xml
https://hibernate.atlassian.net/browse/OGM-1465
> OGM-1465 Run test suite in alphabetical order

- core/src/test/java/org/hibernate/ogm/backendtck/compensation/CompensationSpiTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/CompositeIdQueriesTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedCollectionTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/SimpleQueriesWithTablePerClassNotSupportedTest.java
- core/src/test/java/org/hibernate/ogm/utils/OgmTestCase.java
https://hibernate.atlassian.net/browse/OGM-1471
> OGM-1471 Check Transaction status for Rollback

- bom/pom.xml
- pom.xml
* https://hibernate.atlassian.net/browse/OGM-1475
* https://hibernate.atlassian.net/browse/OGM-1476
> Some additional POM cleanup

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1391
Follow up of [Upgrade to Hibernate ORM 5.3.0.Final](https://hibernate.atlassian.net/browse/OGM-1459).
> OGM-1391 Upgrade to Hibernate Search 5.10.0.Final

- .gitignore
- bom/pom.xml
- featurepack/infinispan-embedded/pom.xml
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/cachehandler/HotRodCacheCreationHandler.java
https://hibernate.atlassian.net/browse/OGM-1480
> OGM-1480 Upgrade Infinispan to 9.3.0.Beta1

- core/src/main/java/org/hibernate/ogm/storedprocedure/impl/NoSQLProcedureOutputsImpl.java
- core/src/test/java/org/hibernate/ogm/test/storedprocedures/UnsupportedProceduresGridDialect.java
- core/src/test/java/org/hibernate/ogm/test/storedprocedures/UnsupportedStoredProcedureCallTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/storedprocedures/InfinispanNamedParametersStoredProcedureCallTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/storedprocedures/ServerTaskInfinispanNamedParametersStoredProcedureCallTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/StoredProceduresDeployer.java
- infinispan-remote/src/test/resources/storedprocedures/servertask/exceptional-procedure
- infinispan-remote/src/test/resources/storedprocedures/servertask/result-set-procedure
- infinispan-remote/src/test/resources/storedprocedures/servertask/simple-value-procedure
A follow up for https://github.com/hibernate/hibernate-ogm/pull/1014
> OGM-1431 Server Tasks for Infinispan Remote

- core/src/main/java/org/hibernate/ogm/hibernatecore/impl/OgmSessionFactoryImpl.java
- core/src/main/java/org/hibernate/ogm/hibernatecore/impl/OgmSessionImpl.java
- core/src/test/java/org/hibernate/ogm/test/criteria/UnsupportedCriteriaForSessionTest.java
https://hibernate.atlassian.net/browse/OGM-1478
So.. next time I think tests are not necessary, you can remind me this PR :)
I think I got all the entry point for using criteria but if I missed some, please. let me know.
Cheers
> OGM-1478 Criteria not supported

- core/src/main/java/org/hibernate/ogm/util/impl/CollectionHelper.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/impl/EmbeddedNeo4jSchemaDefiner.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/impl/BaseNeo4jSchemaDefiner.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/index/impl/Neo4jIndexSpec.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/logging/impl/Log.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/bolt/impl/BoltNeo4jSchemaDefiner.java
- neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/http/impl/HttpNeo4jSchemaDefiner.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/index/CypherQueriesCreationForIndexesTest.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/index/Neo4jIndexTest.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/mapping/UniqueConstraintTest.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/util/ExceptionHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/BoltNeo4jTestHelperDelegate.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/EmbeddedNeo4jTestHelperDelegate.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/HttpNeo4jTestHelperDelegate.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelperDelegate.java
https://hibernate.atlassian.net/browse/OGM-1462
Follows https://github.com/hibernate/hibernate-ogm/pull/1015
The details are in each commit but, in short, I added some testcase and move the the test for getting and controlling the index during test to the delegate classes.
I also change the test cases to make sure that only the expected indexes exist in the database. To make this work we need to delete the indexes and constraint created by previous tests.
Cheers,
Davide
> OGM-1462 Support indexes with Neo4j

- integrationtest/pom.xml
- mongodb/pom.xml
- pom.xml
Removing this stuff - which seems no longer necessary - will avoid a lot of logs noise when debugging other issues on more recent JVMs.
- https://hibernate.atlassian.net/browse/OGM-1504
> OGM-1504 Remove usage of the groovy-maven-plugin

- pom.xml
https://hibernate.atlassian.net/browse/OGM-1506
> OGM-1506 Introduce a Maven profile to test on JDK10

- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protobuf/schema/SchemaValidator.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamSerializerSetup.java
https://hibernate.atlassian.net/browse/OGM-1510
> OGM-1510 Remove some references to protostream internals

- core/src/test/java/org/hibernate/ogm/sessionfactory/SessionFactoryBuilder.java
- core/src/test/java/org/hibernate/ogm/utils/TestHelper.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/impl/MongoDBSchemaDefiner.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/index/MongoDBIndexOptionsConflictsTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/index/MongoDBIndexTest.java
https://hibernate.atlassian.net/browse/OGM-1496
The first commit is only to add new in line test helper.
> OGM-1496 Handle indexes and constraints on same columns 

- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/InfinispanRemoteDialect.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/InfinispanRemoteDatastoreProvider.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protobuf/CompositeProtobufCoDec.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/OgmProtoStreamMarshaller.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtoDataMapper.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamId.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamPayload.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamSerializerSetup.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/multimessage/MultiMessage.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/multimessage/MultiMessageExtension.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/schema/TableDefinition.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/sequences/HotRodSequenceHandler.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/sequences/HotRodSequencer.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/sequences/SequencesPerCache.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
https://hibernate.atlassian.net/browse/OGM-1511
> OGM-1511 Remove thread local serializzation context

- core/src/main/java/org/hibernate/ogm/dialect/batch/spi/OperationsQueue.java
- core/src/main/java/org/hibernate/ogm/dialect/impl/BatchOperationsDelegator.java
- core/src/main/java/org/hibernate/ogm/persister/impl/EntityAssociationUpdater.java
- core/src/test/java/org/hibernate/ogm/backendtck/inheritance/singletable/family/SingleTableInheritancePersistTest.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/InfinispanRemoteDialect.java
https://hibernate.atlassian.net/browse/OGM-1512
> OGM-1512 Flush operation after a cascade delete could prejudice commit

- core/src/test/java/org/hibernate/ogm/backendtck/compensation/CompensationSpiTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/optimisticlocking/OptimisticLockingTest.java
- core/src/test/java/org/hibernate/ogm/backendtck/queries/SimpleQueriesTest.java
- documentation/manual/src/main/asciidoc/modules/infinispan.asciidoc
- infinispan-embedded/src/main/java/org/hibernate/ogm/datastore/infinispan/impl/TransactionManagerLookupDelegator.java
- infinispan-remote/pom.xml
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/InfinispanRemoteProperties.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/configuration/impl/InfinispanRemoteConfiguration.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/HotRodClientBuilder.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/InfinispanRemoteDatastoreProvider.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/cachehandler/HotRodCacheCreationHandler.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protostream/ProtostreamPayload.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/initialize/InfinispanRemotePerformanceTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/query/nativequery/InfinispanRemoteSessionNativeQueryTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/transaction/InfinispanRemoteLockingTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/TransactionalRemoteCacheCounter.java
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/infinispanremote/HotRodSearchIntegrationIT.java
https://hibernate.atlassian.net/browse/OGM-1494
This is a preview of supporting HotRod transactions,
Many tests didn't work yet.
The major issues are: 
* Thread local context (solved by another PR)
* size and query apis are not transactional :(
> OGM-1494 Infinispan HotRod transaction support

- core/src/test/java/org/hibernate/ogm/backendtck/optimisticlocking/OptimisticLockingTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/transaction/InfinispanRemoteLockingTest.java
Remove a protected variable in favor of constructors.
@fax4ever  A small change I would like to apply to your PR
Please, merge it on master if you think it's OK.
Cheers
> OGM-1494 Refactor OptimisticLockingTest

- infinispan-embedded/src/test/java/org/hibernate/ogm/datastore/infinispan/test/cachemapping/LocalDateTimeMappingTest.java
- infinispan-embedded/src/test/java/org/hibernate/ogm/datastore/infinispan/utils/InfinispanTestHelper.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/mapping/LocalDateTimeMappingTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/mapping/LocalDateTimeMappingTest.java
- neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/mapping/LocalDateTimeMappingTest.java
https://hibernate.atlassian.net/browse/OGM-1519
> OGM-1519 Test java.time fields are mapped to the correct type

- bom/pom.xml
- core/src/test/java/org/hibernate/ogm/backendtck/storedprocedures/PositionalParametersStoredProcedureCallTest.java
https://hibernate.atlassian.net/browse/OGM-1522
https://hibernate.atlassian.net/browse/OGM-1525
Upgrade to Hibernate ORM 5.3.6.Final
Upgrade to Hibernate Search 5.10.4.Final
> OGM-1522 Upgrade to Hibernate ORM 5.3.6.Final

- core/src/test/java/org/hibernate/ogm/backendtck/queries/parameters/QueryWithParametersTest.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/protobuf/ByteProtofieldAccessor.java
- infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/query/impl/InfinispanRemoteQueryHandler.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/mapping/ByteEntity.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/mapping/ByteMappingTest.java
- infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/query/parameter/QueryWithParametersTest.java
- infinispan-remote/src/test/resources/protoschema-expectations/allTypesGenerationTest.protobuf
https://hibernate.atlassian.net/browse/OGM-1458
See also: https://github.com/infinispan/infinispan/pull/6191
> OGM-1458 Change mapping of byte type field to ProtoBuf int32

- bom/pom.xml
- featurepack/infinispan-embedded/pom.xml
https://hibernate.atlassian.net/browse/OGM-1528
> OGM-1528 Upgrade to Infinispan 9.4.0.Final

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1534
> OGMM-1534 Update to Neo4j 3.4.9

- documentation/manual/src/main/asciidoc/modules/mapping.asciidoc
At the moment Hibernate OGM doesn't support it.
> OGM-1237 Remove reference to @OrderBy from the documentation

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1541
> OGM-1541 Upgrade Jackson to 2.9.5 (WF 13.0.0)

- bom/pom.xml
https://hibernate.atlassian.net/browse/OGM-1548
https://hibernate.atlassian.net/browse/OGM-1549
https://hibernate.atlassian.net/browse/OGM-1550
> Minor Updates of the libraries in Neo4j and MongoDB

- pom.xml
- src/main/build-config/checkstyle.xml
https://hibernate.atlassian.net//browse/OGM-1558
> OGM-1558 Upgrade to checkstyle 8.18 and maven-checkstyle-plugin 3.0.0

- pom.xml
- settings-example.xml
https://hibernate.atlassian.net/projects/OGM/issues/OGM-1562
https://hibernate.atlassian.net/projects/OGM/issues/OGM-1563
Update plugins and download dependecies using HTTPS during build.
> OGM-1563/OGM-1562 Security updates

- .github/workflows/build.yml
- mongodb/pom.xml
Fix [OGM-1591](https://hibernate.atlassian.net/browse/OGM-1591)
[OGM-1591]: https://hibernate.atlassian.net/browse/OGM-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests with remote servers on GitHub

- .github/workflows/build.yml
- bom/pom.xml
- featurepack/mongodb/pom.xml
- featurepack/mongodb/src/main/modules/ogm/mongodb/module.xml
- integrationtest/src/test/java/org/hibernate/ogm/test/integration/mongodb/wildflynosql/MongoDBWildFlyNoSQLMemberRegistrationIT.java
- integrationtest/wildfly-server-testconfig/standalone-nosql.xml
- mongodb/pom.xml
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/configuration/impl/MongoDBConfiguration.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/impl/MongoDBDatastoreProvider.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/options/AuthenticationMechanismType.java
- mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/options/WriteConcernType.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/datastore/DatastoreInitializationTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/datastore/WriteConcernTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/index/MongoDBIndexOptionsConflictsTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/index/MongoDBIndexTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/options/writeconcern/WriteConcernAnnotationTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/options/writeconcern/WriteConcernOptionTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/options/writeconcern/WriteConcernPropagationTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/MongoDBSessionCLIQueryTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/nativequery/OscarWildePoem.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/query/parsing/MongoDBQueryParsingTest.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MockMongoClientBuilder.java
- mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/utils/MongoDBTestHelper.java
Fix https://hibernate.atlassian.net/jira/software/c/projects/OGM/issues/OGM-1588
Based on https://github.com/hibernate/hibernate-ogm/pull/1127
Supersedes https://github.com/hibernate/hibernate-ogm/pull/1127
> Upgrade MongoDB driver dependency to mongodb-driver-legacy 4.11.3

- bom/pom.xml
- ci/release/Jenkinsfile
- documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
- how-to-release.md
Fix https://hibernate.atlassian.net/browse/OGM-1594
> Add Jenkinsfile pipeline configuration

- README.md
- bom/pom.xml
- documentation/manual/src/main/asciidoc/modules/how-to-contribute.asciidoc
- how-to-release.md
- pom.xml
- src/main/release-scripts/update-version.sh
> Update repository configuration
