hibernate/hibernate-ogm

core/src/test/java/org/hibernate/ogm/backendtck/queries/AnotherEmbeddable.java
core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedTest.java
core/src/test/java/org/hibernate/ogm/backendtck/queries/SimpleQueriesTest.java
core/src/test/java/org/hibernate/ogm/backendtck/queries/WithEmbedded.java
mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/query/parsing/impl/MongoDBPredicateFactory.java
mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/id/objectid/ObjectIdWithEmbeddableTest.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/cypherdsl/impl/CypherDSL.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/EmbeddedAliasTree.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/Neo4jPropertyHelper.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/Neo4jQueryRendererDelegate.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/Neo4jQueryResolverDelegate.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/predicate/impl/Neo4jPredicateFactory.java
neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/query/parsing/Neo4jQueryResolverDelegateTest.java

https://hibernate.atlassian.net/browse/OGM-692
Rebased for 4,2 branch
To create the queries in Neo4j I need to create and keep track of aliases for the various embedded nodes using a tree structure. Alias are created starting form the alias of the entity and adding the position of the
node as a suffix.
For example, an embedded represented in the query as *n.embedded.anotherEmbedded* will generate the following aliases *n_0* for (n.embedded) and *n_0_0* for (n.embedded.anotherEmbedded).
The following query
```
FROM WithEmbedded e
WHERE e.anEmbeddable.anotherEmbeddable.embeddedString = 'string 2'
``` 
becomes:
```
MATCH (e:WithEmbedded)
OPTIONAL MATCH (e) -[:anEmbeddable]-> (`e_0`:EMBEDDED) -[:anotherEmbeddable]->(`e_0_0`:EMBEDDED)
WHERE `e_0_0`.embeddedString="string 2"
RETURN e
```
I …

OGM-692 Query on embedded properties for Neo4j (and MongoDB)

---

couchdb/pom.xml
ehcache/pom.xml
infinispan/pom.xml
mongodb/pom.xml
neo4j/pom.xml
pom.xml

Turns out, it also scans the classified JAR when specifying the dependency name.

[4.2] OGM-778 Running TCK tests from test JAR itself rather than unpacking

---

documentation/manual/pom.xml
documentation/manual/src/main/asciidoc/en-US/modules/configuration.asciidoc
integrationtest/couchdb/src/test/resources/jboss-deployment-structure-couchdb.xml
integrationtest/pom.xml
integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/util/ModuleMemberRegistrationDeployment.java
integrationtest/testcase/src/test/resources/jboss-deployment-structure-ehcache.xml
modules/pom.xml
modules/wildfly/pom.xml
modules/wildfly/src/main/assembly/dist.xml
modules/wildfly/src/main/modules/hql/module.xml
modules/wildfly/src/main/modules/ogm/infinispan/module.xml
modules/wildfly/src/main/modules/ogm/neo4j-lucene/module.xml
modules/wildfly/src/main/modules/ogm/neo4j/module.xml
pom.xml
src/main/release-scripts/upload_distribution.sh

This has been tested successfully with WildFly 9.0.0.CR2-SNAPSHOT, but the PR refers to 9.0.0.CR1 (both work).
Some points of interest:
- I had to better hide the Lucene version used by Neo4J as classloader precedence in WF9 would otherwise expose it to the wrong Lucene version
- the custom Lucene module uses the 'org.hibernate.ogm.neo4j.lucene' module id to prevent slot conflicts with other projects (this being the one provided by OGM)
- turns out some slot definitions were wrong 
- this does replace (remove) the support for WildFly 8, as agreed on the mailing list.
- the artifact id for Arquillian changed
The download/unpacking of the Hibernate Search and Infinispan modules for integration tests - not needed in this specific version - is simply commented out as I don't think it's worth …

Support WildFly 9

---

bom/pom.xml
modules/wildfly/src/main/assembly/dist.xml
modules/wildfly/src/main/modules/ogm/redis-driver/module.xml

Using lettuce 3.2.Final with netty 4.0.26 runs into a deadlock/infinite wait when the connection runs into a connection refused. Ship own netty jars until then.

OGM-886 Ship own netty jars to omit connection-refused-bug

---

core/src/main/java/org/hibernate/ogm/datastore/document/impl/DotPatternMapHelpers.java
core/src/main/java/org/hibernate/ogm/dialect/impl/DotPatternMapHelpers.java
redis/src/main/java/org/hibernate/ogm/datastore/redis/RedisDialect.java
redis/src/main/java/org/hibernate/ogm/datastore/redis/dialect/model/impl/RedisAssociationRowFactory.java
redis/src/main/java/org/hibernate/ogm/datastore/redis/dialect/value/Entity.java
redis/src/test/java/org/hibernate/ogm/datastore/redis/test/associations/ManyToOneInEntityJsonRepresentationTest.java
redis/src/test/java/org/hibernate/ogm/datastore/redis/test/embeddable/EmbeddableMappingTest.java

* Don't map elements within embeddable collections using dot names
* Remove the common prefixes from the JSON representation
* Refactor parts of MongoHelpers into DotPatternMapHelpers

OGM-887 Don't map elements within embeddable collections using dot names

---

bom/pom.xml
integrationtest/couchdb/src/test/resources/jboss-deployment-structure-couchdb.xml
integrationtest/mongodb/src/test/java/org/hibernate/ogm/test/integration/jboss/MongoDBModuleMemberRegistrationIT.java
integrationtest/neo4j/src/test/java/org/hibernate/ogm/test/integration/jboss/Neo4jJtaModuleMemberRegistrationIT.java
integrationtest/neo4j/src/test/java/org/hibernate/ogm/test/integration/jboss/Neo4jResourceLocalModuleMemberRegistrationIT.java
integrationtest/pom.xml
integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationIT.java
integrationtest/redis/src/test/java/org/hibernate/ogm/test/integration/jboss/RedisModuleMemberRegistrationWithTTLConfiguredIT.java
integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/EhcacheModuleMemberRegistrationIT.java
integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/InfinispanModuleMemberRegistrationIT.java
integrationtest/testcase/src/test/java/org/hibernate/ogm/test/integration/jboss/ModulesMagicDeckITCassandra.java
integrationtest/testcase/src/test/resources/jboss-deployment-structure-ehcache.xml
modules/pom.xml
modules/wildfly/src/main/assembly/dist.xml
modules/wildfly/src/main/modules/ogm/cassandra/module.xml
modules/wildfly/src/main/modules/ogm/core/module.xml
modules/wildfly/src/main/modules/ogm/couchdb/module.xml
modules/wildfly/src/main/modules/ogm/ehcache/module.xml
modules/wildfly/src/main/modules/ogm/infinispan/module.xml
modules/wildfly/src/main/modules/ogm/mongodb/module.xml
modules/wildfly/src/main/modules/ogm/neo4j/module.xml
modules/wildfly/src/main/modules/ogm/redis/module.xml

Integration tests use WF 10 stock modules now. Also adapting to changed module id/slot.

OGM-878 Upgrading to WF 10 Beta1, Hibernate ORM 5 CR4

---

core/src/main/java/org/hibernate/ogm/datastore/document/impl/DotPatternMapHelpers.java
couchdb/pom.xml
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/CouchDBDialect.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/backend/json/impl/EntityDocument.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/model/impl/CouchDBAssociation.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/model/impl/CouchDBAssociationRowFactory.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/model/impl/CouchDBAssociationSnapshot.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/model/impl/DocumentBasedAssociation.java
couchdb/src/main/java/org/hibernate/ogm/datastore/couchdb/dialect/model/impl/EmbeddedAssociation.java
couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/test/associations/MapMappingTest.java
couchdb/src/test/java/org/hibernate/ogm/datastore/couchdb/utils/CouchDBTestHelper.java
documentation/manual/src/main/asciidoc/en-US/modules/couchdb.asciidoc
mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
redis/src/main/java/org/hibernate/ogm/datastore/redis/RedisDialect.java

- Fix properties with dot path names of embedded documents by converting those to nested objects
- Extract common parts from RedisDialect to DotPatternMapHelpers
- Adjust docs
Hint: I wasn't able to run the full test suite successfully even before the change. Need your advice then.

OGM-904 Use more natural format to store map-typed properties in CouchDB

---

core/src/test/java/org/hibernate/ogm/utils/GridDialectType.java
core/src/test/java/org/hibernate/ogm/utils/GridModule.java
core/src/test/java/org/hibernate/ogm/utils/SkipByDatastoreProvider.java
core/src/test/java/org/hibernate/ogm/utils/SkippableTestRunner.java
core/src/test/java/org/hibernate/ogm/utils/TestHelper.java
core/src/test/java/org/hibernate/ogm/utils/test/SkipByDatastoreProviderClassLevelSelfTest.java
core/src/test/java/org/hibernate/ogm/utils/test/SkipByDatastoreProviderSelfJpaTest.java

* Refactor annotations and testrunner
* Adjust datastore provider lookup within the test to support class names/short names and to deal with type hierarchies
* Add SkipByGridDialect annotation that evaluates the dialect from the configuration

OGM-929 Refactor test runners for skip by provider and skip by dialect

---

core/src/main/java/org/hibernate/ogm/persister/impl/EntityAssociationUpdater.java
core/src/main/java/org/hibernate/ogm/util/impl/AssociationPersister.java
core/src/main/java/org/hibernate/ogm/util/impl/Log.java
core/src/test/java/org/hibernate/ogm/backendtck/associations/manytoone/Employee.java
core/src/test/java/org/hibernate/ogm/backendtck/associations/manytoone/Employeer.java
core/src/test/java/org/hibernate/ogm/backendtck/associations/manytoone/Employer.java
core/src/test/java/org/hibernate/ogm/backendtck/associations/manytoone/ManyToOneTest.java
core/src/test/java/org/hibernate/ogm/utils/TestHelper.java

Supersedes #597: No exception anymore, instead the associated entity is loaded to make the same flow of execution work as in ORM.

OGM-931 Allowing to persist association to unmanaged entity on inverse side

---

cassandra/pom.xml
cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/model/impl/ResultSetTupleIterator.java
cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/type/impl/CassandraTrueFalseType.java
cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/type/impl/CassandraYesNoType.java
cassandra/src/main/java/org/hibernate/ogm/datastore/cassandra/type/impl/CharacterStringGridTypeDescriptor.java
cassandra/src/test/java/org/hibernate/ogm/datastore/cassandra/test/mapping/CassandraBooleanCharacterTypeTest.java

Boolean types mapped to Yes/No or True/False should be mapped to 'Y'/'N' or 'T'/'F' characters. Since Cassandra does not currently support the character data type, they should be single character strings. 
There is evidence in the code that this was the expected mapping, anyway, that fields are incorrectly mapped to "true" or "false" (strings).
I've implemented the change to fix the behavior and written unit tests. I added mockito to the pom test dependencies.
As suggested by @gunnarmorling, I've tried using the TranslatingGridTypeDescriptor to fix the issue, without success.

OGM-962 Fix Yes/No and True/False type mapping in Cassandra

---

mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java
mongodb/src/test/java/org/hibernate/ogm/datastore/mongodb/test/index/MongoDBIndexTest.java

identifying a constraint violation on the primary key
Note: I removed the dropIndexes call as it's useless and counter productive when we have several tests.

OGM-910 Make the index tests work on Fongo and relax the regexp

---

.travis.yml
settings-example.xml

https://hibernate.atlassian.net/browse/OGM-1090
In passing, remove the sed calls adding this for the Travis build.
Note, I'm using the default Central repository instead of the Google
mirror as apparently a few artifacts are missing on Google mirror.
The default Central repository is now hosted by Fastly and is very fast.

OGM-1090 Use Central first to get the artifacts

---

core/src/main/java/org/hibernate/ogm/dialect/impl/GridDialectInitiator.java
core/src/main/java/org/hibernate/ogm/util/impl/Log.java
core/src/test/java/org/hibernate/ogm/test/boot/GridDialectInitiatorTest.java
core/src/test/java/org/hibernate/ogm/test/boot/InvalidGridDialect.java

https://hibernate.atlassian.net/browse/OGM-1104
If the GridDialect does not have a valid constructor, we
ignored the error and we threw a NPE instead of an explicit error
message.
In passing, fix the error message.

OGM-1104 Properly throw an exception in GridDialectInitiator

---

.travis.yml
bom/pom.xml
modules/wildfly/pom.xml
modules/wildfly/src/main/assembly/dist.xml
modules/wildfly/src/main/modules/ogm/neo4j-internal/module.xml
modules/wildfly/src/main/modules/ogm/neo4j/module.xml
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/BaseNeo4jDialect.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/embedded/impl/EmbeddedNeo4jGraphDatabaseFactory.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/predicate/impl/Neo4jInPredicate.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/predicate/impl/Neo4jIsNullPredicate.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/query/parsing/impl/predicate/impl/Neo4jLikePredicate.java
neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/remote/json/impl/Row.java
neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/Neo4jGraphDatabaseServiceLoaderTest.java

https://hibernate.atlassian.net/browse/OGM-1026
This version still requires Apache Lucene 5.5, I was wrong about it when we talked in chat.
Changes in the new version:
* the Rest API response has an additional field `meta` that needs to be mapped in
`org.hibernate.ogm.datastore.neo4j.remote.json.imp.Row`;
* libraries need to be updated in the WildFly module;
* the operator `HAS` in cypher has been replaced by `EXISTS`;
* some changes in the signature of methods used when dealing with the embedded datastore.

OGM-1026 Support Neo4j 3.0.3

---

mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBDialect.java

https://hibernate.atlassian.net/browse/OGM-1115
More modern versions of MongoDB have a different syntax.
The regexp we use now should be sufficiently future proof.
I'm not very fond of this and we should probably try to get the MongoDB people to differentiate the 2 exceptions but IIRC the server doesn't do any difference between the 2.

OGM-1115 Relax regexp used to detect primary key constraint violation

---

.gitignore
distribution/src/main/assembly/dist.xml

And additional cleanup to the distribution.
* https://hibernate.atlassian.net/browse/OGM-1146

OGM-1146 Properly ignore hibernate-noorm-release-scripts directory

---

infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/InfinispanRemoteProperties.java
infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/configuration/impl/InfinispanRemoteConfiguration.java
infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/impl/HotRodClientBuilder.java
infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/logging/impl/Log.java
infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/initialize/InfinispanRemoteConfigurationTest.java
infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/InfinispanRemoteTestHelper.java

https://hibernate.atlassian.net/browse/OGM-1162
I built this on top of https://github.com/hibernate/hibernate-ogm/pull/785
I think it is OK to provide a way to setup the client using parameters in addition to the resource file.
This allows a user to override default values or write tests more easily.
@Sanne let me know which other options you think we need to require. I didn't add a warning for those options that are harmless (it's easy to add if you feel strong about it).

OGM-1162 Validate configuration for HotRod

---

core/src/main/java/org/hibernate/ogm/loader/impl/OgmLoader.java

With the current code the resultSet can never be null, if that happens,
you have NullPointerException before calling the method.
I prefer to remove the code for now and eventually put the check back if we
have a use case where it makes sense.

OGM-1191 Remove dead code warning in OgmLoader

---

bom/pom.xml
documentation/manual/src/main/asciidoc/en-US/modules/mongodb.asciidoc
mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/MongoDBProperties.java
mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/configuration/impl/MongoDBConfiguration.java

https://hibernate.atlassian.net/browse/OGM-1240
https://hibernate.atlassian.net/browse/OGM-1241
MongoDB uses an authentication database to verify the credentials, this might differ fomr the database we want to connect. I've added a new property with default value to admin.
THe only problem that I have with this issue is that it is complicated to test with a job.
I've created [OGM-1242](https://hibernate.atlassian.net/browse/OGM-1242) to keep track of it.
I've also upgraded the driver in the process.

OGM-1240, OGM-1241 MongoDB authentication fails

---

bom/pom.xml
core/pom.xml
integrationtest/pom.xml
jipijapa/src/main/java/org/wildfly/jpa/hibernateogm5/HibernateOGMPersistenceProviderAdaptor.java
modules/src/main/aliases/org/hibernate/search/engine/module.xml
modules/src/main/assembly/dist.xml
neo4j/pom.xml
performance/pom.xml
pom.xml

* https://hibernate.atlassian.net/browse/OGM-1361
* https://hibernate.atlassian.net/browse/OGM-1369
This is a partial backport of my work supporting ORM 5.2 (for which upgrading to WF 11 was necessary).
OGM 5.2 modules will be released as WF 11 modules. Note that, contrary to the other versions, it uses the main slot for ORM as OGM 5.2 uses ORM 5.1 and it is the version bundled with WF 11.
I also upgraded Search to 5.6.4.Final.

OGM-1361 Build modules for WildFly 11

---

bom/pom.xml
distribution/pom.xml

https://hibernate.atlassian.net//browse/OGM-1372
See also hibernate/hibernate-noorm-release-scripts#4 for more information about how this `dist` directory will be uploaded.
Note this also fixes an issue: the WildFly module would not be uploaded to Sourceforge without this change, because it doesn't match the pattern in the release script (`*-wildfly-10-*` vs. `wildfly-11`).

OGM-1372 Put the distribution files to upload into distribution/target/dir so that release scripts find them

---

infinispan-remote/infinispan-server-provisioning.xml
infinispan-remote/pom.xml
infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/RemoteHotRodServerRule.java
integrationtest/infinispan-server-provisioning.xml
integrationtest/pom.xml
integrationtest/server-provisioning.xml
pom.xml

This is to make it possible for us to consume feature packs soon, as e.g. Hibernate Search & Infinispan will start producing them.
Also happens to make our testsuite a bit lighter.
- https://hibernate.atlassian.net/browse/OGM-1373
- https://hibernate.atlassian.net/browse/OGM-1374
Later we should have OGM also produce "feature packs", and this will be useful to run integration tests on our own built packs.

Infinispan server provisioning

---

neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/remote/RemoteAuthenticationFailureTest.java

* https://hibernate.atlassian.net/browse/OGM-1377
If the exception is not a HibernateException, it's better to let the test throw the exception as we have a more informative message (done to diagnose a failure on CI).

OGM-1377 Make RemoteAuthenticationFailureTest failures more informative

---

neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/test/remote/RemoteAuthenticationFailureTest.java
neo4j/src/test/java/org/hibernate/ogm/datastore/neo4j/utils/Neo4jTestHelper.java

https://hibernate.atlassian.net/browse/OGM-1379
It turns out that the tests wasn't reading the right variables and also ci was launching the build with the wrong parameters.
This should fix the error we have on CI

OGM-1379 Pass the right parameters to RemoteAuthenticationFailureTest

---

core/src/test/java/org/hibernate/ogm/backendtck/id/TableNextValueTableNameTest.java
infinispan-embedded/src/main/java/org/hibernate/ogm/datastore/infinispan/persistencestrategy/counter/TableClusteredCounterHandler.java

https://hibernate.atlassian.net/browse/OGM-1397
Is it OK to include it for the next release?
If they update the library, people might have problem since the name of the counters has changed

OGM-1397 Counter name should contain the table for @TableGenerator

---

documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
integrationtest/pom.xml
integrationtest/src/test/resources/arquillian.xml
pom.xml

https://hibernate.atlassian.net/browse/OGM-1413
Wildfly 12 has a partial support of JEE8, for instance CDI 2.0 is supported, not JPA 2.2.
We need to patch WF using JPA 2.2 patch for WF12.
We need to start the server with -Dee8.preview.mode=true to enable CDI 2.0.

OGM-1413 Upgrade Wildfly distribution to 12.0.0

---

core/src/main/java/org/hibernate/ogm/hibernatecore/impl/OgmSessionImpl.java

https://hibernate.atlassian.net/browse/OGM-1460
When we upgraded to ORM 5.2 we had some failures because it wasn't possible anymore to
use the getTransaction() method in a JTA environment. We updated our tests since then and it
seems that this issue has been solved.
@fax4ever , this should be a quick one, let's just wait if it passes all the builds on CI.

OGM-1460 In OgmSessionImpl, don't override the getTransaction() method

---

neo4j/src/main/java/org/hibernate/ogm/datastore/neo4j/dialect/impl/BaseNeo4jAssociationQueries.java

Running CREATE UNIQUE queries will generate the following warning:
```
The RULE planner is not available in the current CYPHER version,
the query has been run by an older CYPHER version. CREATE UNIQUE is unsupported
for current CYPHER version, the query has been execute by an older CYPHER version
```
https://hibernate.atlassian.net/browse/OGM-1474

OGM-1474 Replace CREATE UNIQUE in Cypher queries with MERGE

---

bom/pom.xml
documentation/examples/wildfly-quickstart/pom.xml
documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/OGM-1499
Unfortunately 5.2 Hibernate Search slot version is already taken in WildFly 13.0.0.Final, provisioned with Hibernate Search 5.10.1.Final, requiring Hibernate ORM 5.3.1.Final.
But the actual version of Hibernate OGM requires ORM 5.3.0.Final.

OGM-1499 Update integration tests to use WildFly 13.0.0.Final

---

core/src/main/java/org/hibernate/ogm/util/configurationreader/impl/SimplePropertyReaderContext.java
documentation/manual/src/main/asciidoc/modules/infinispan.asciidoc
infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/initialize/DisneyCharacter.java
infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/test/initialize/MinimalHotRodConfigTest.java
infinispan-remote/src/test/resources/hotrodclient-minimal.properties

https://hibernate.atlassian.net/browse/OGM-1518
I've just added a test case.
It seems that everything works even with an empty `hotrodclient.properties`-
Does the issue make sense? Or shall we solve it as `Out Of Date`?
Additional question: Does it make sense to override  the Infinispan defaults?

OGM-1518 Test empty hotrodclient.properties

---

bom/pom.xml
documentation/manual/pom.xml
documentation/manual/src/main/asciidoc/modules/configuration.asciidoc
featurepack/core/pom.xml
featurepack/core/src/main/feature-pack-def/feature-pack-template.xml
featurepack/core/src/main/modules/ogm/jipijapa/module.xml
integrationtest/pom.xml
integrationtest/server-provisioning.xml
pom.xml

https://hibernate.atlassian.net/browse/OGM-1523

OGM-1523 Use WildFly 14 default Hibernate Search and ORM

---

core/src/main/java/org/hibernate/ogm/util/configurationreader/impl/Validators.java
infinispan-remote/src/main/java/org/hibernate/ogm/datastore/infinispanremote/configuration/impl/InfinispanRemoteValidators.java
pom.xml

Hi. I wanted to check if the Neo4j Java driver could be upgrade with a decent amount of pain to a 4.x series and the whole project failed to build due to an incompatible mix of versions between Checkstyle itself and the Maven plugin. This PR fixes this and also removes 2 check style violations.

OGM-1580 - Upgrade to a Checkstyle 8.29 compatible version of the plugin and fix remaining issues.

---

mongodb/src/main/java/org/hibernate/ogm/datastore/mongodb/impl/MongoDBDatastoreProvider.java

This change allows users to track which connections are coming from hibernate-ogm by examining the MongoDB server logs, by looking for log statements like this:
```
{
"t": {
"$date": "2024-09-05T11:52:33.248-04:00"
},
"s": "D2",
"c": "COMMAND",
"id": 21965,
"ctx": "conn304",
"commandArgs": {
"isMaster": 1,
"helloOk": true,
"client": {
"driver": {
"name": "mongo-java-driver|legacy|hibernate-ogm",
"version": "4.11.3|5.4.2"
},
"os": {
"type": "Darwin",
"name": "Mac OS X",
"architecture": "x86_64",
"version": "14.6.1"
},
"platform": "Java/Amazon.com Inc./1.8.0_422-b05"
},
"$db": "admin"
}
}
```
Note the driver name and version refer to both the underlying MongoDB Java driver and hibernate-ogm.
https://hibernate.atlassian.net/browse/OGM-1589

OGM-1589: Add hibernate-ogm metadata to MongoClient construction

---

documentation/manual/src/main/asciidoc/migration/index.asciidoc

https://hibernate.atlassian.net/browse/OGM-1592

OGM-1592: Add 5.4.2.Final migration guide

---

documentation/manual/src/main/asciidoc/index.asciidoc
documentation/manual/src/main/asciidoc/modules/migrating.asciidoc

Fix [OGM-1592](https://hibernate.atlassian.net/browse/OGM-1592)
It wasn't actually generated
Keeping it as part of the documentation because
the ascidoctor plugin seems to ignore it otherwise and
I don't want to spend more time on it.
Probably, we would need to upgrade the plugin.
[OGM-1592]: https://hibernate.atlassian.net/browse/OGM-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix rendering of the migration guide
